export default class SignInElements {

  url                = "http://automationpractice.com/index.php?controller=authentication&back=my-account"
  fieldEmail         = "#email_create"
  btnCreateAnAccount = "#SubmitCreate"
  btnSignIn          = "#SubmitLogin"
  btnMr              = "#uniform-id_gender1"
  btnMiss            = "#uniform-id_gender2"
  fieldPassword      = "#passwd"
  fieldFirstName     = "#customer_firstname"
  fieldLastName      = "#customer_lastname"
  btnDayOfBirth      = "#days"
  btnMonthOfBirth    = "#months"
  btnYearOfBirth     = "#years"
  fieldCompany       = "#company"
  fieldAddress       = "#address1"
  fieldCity          = "#city"
  btnState           = "#id_state"
  fieldPostCode      = "#postcode"
  fieldPhone         = "#phone"
  btnRegister        = "#submitAccount"
  tilteInvalidPhone  = "#center_column > div > ol > li"
}
